NUM_ROWS, NUM_COLUMNS = 12, 24
TILE_SIZE = 28
PANEL_SIZE = 200
GRID_WIDTH = NUM_ROWS * TILE_SIZE
GRID_HEIGHT = NUM_COLUMNS * TILE_SIZE
WINDOW_WIDTH = GRID_WIDTH + PANEL_SIZE
WINDOW_HEIGHT = GRID_HEIGHT + 1
